### ISSUE TITLE
Bug in projects in the projects section

### ISSUE THREAD

**Issue by mepsrajput** [mepsrajput/mepsrajput.github.io#1]
When clicking on the **i** button the **overlay** should _scroll up_ smoothly and when clicking again, it must scroll down (or in other words should get invisible). Currently, it's not happening.

**Comment by praveen-me** [comment]
Here @mepsrajput I thought I worked correctly.
Check out correctly.

**Comment by mepsrajput** [comment]
**Solved**. Problem was in css.

**Comment by mepsrajput** [comment]
Solved. Problem was in css.
